version: '3.3'

services:

  db:
    image: mysql:5.7
    volumes:
      - uniquename_db_data:/var/lib/mysql
      - ./wp-content:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 9191:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

  wp:
    image: tatemz/wp-cli
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    links:
      - db:mysql
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  uniquename_db_data:
